"""initial schema

Revision ID: a317e7e4a698
Revises: 
Create Date: 2026-08-07 23:26:26.068138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a317e7e4a698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stated_total', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciliation_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('nu', sa.Float(), nullable=False),
    sa.Column('q05', sa.Float(), nullable=False),
    sa.Column('q25', sa.Float(), nullable=False),
    sa.Column('q50', sa.Float(), nullable=False),
    sa.Column('q75', sa.Float(), nullable=False),
    sa.Column('q95', sa.Float(), nullable=False),
    sa.Column('p_positive', sa.Float(), nullable=False),
    sa.Column('drift_source', sa.String(length=32), nullable=False),
    sa.Column('garch_identified', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('resolve_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_json', sa.Text(), nullable=True),
    sa.CheckConstraint('(garch_identified = 0 AND rejection_reason IS NOT NULL) OR (garch_identified = 1 AND rejection_reason IS NULL)', name='ck_forecasts_rejection_reason_iff_rejected'),
    sa.CheckConstraint('data_asof <= created_at', name='ck_forecasts_no_lookahead'),
    sa.CheckConstraint('horizon_days > 0', name='ck_forecasts_positive_horizon'),
    sa.CheckConstraint('nu >= 2.0', name='ck_forecasts_nu_defined_variance'),
    sa.CheckConstraint('p_positive >= 0.0 AND p_positive <= 1.0', name='ck_forecasts_p_positive_is_probability'),
    sa.CheckConstraint('q05 <= q25 AND q25 <= q50 AND q50 <= q75 AND q75 <= q95', name='ck_forecasts_quantiles_ordered'),
    sa.CheckConstraint('resolve_at > created_at', name='ck_forecasts_resolves_in_future'),
    sa.CheckConstraint('sigma > 0', name='ck_forecasts_positive_sigma'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_resolve_at'), ['resolve_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_forecasts_ticker_horizon', ['ticker', 'horizon_days'], unique=False)

    op.create_table('model_versions',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('promoted_from', sa.String(length=64), nullable=True),
    sa.Column('validation_evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_from'], ['model_versions.version'], ),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('provenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_asof', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('missing_json', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('data_asof IS NULL OR data_asof <= fetched_at', name='ck_provenance_no_lookahead'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_records_endpoint'), ['endpoint'], unique=False)

    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claims_json', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('epistemic_tags', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_ticker'), ['ticker'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_asof', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_positions_positive_price'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', name='uq_positions_account_ticker')
    )
    op.create_table('resolutions',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('pit', sa.Float(), nullable=False),
    sa.Column('realized_return', sa.Float(), nullable=False),
    sa.Column('log_score', sa.Float(), nullable=False),
    sa.CheckConstraint('actual_price > 0', name='ck_resolutions_positive_price'),
    sa.CheckConstraint('pit >= 0.0 AND pit <= 1.0', name='ck_resolutions_pit_is_probability'),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolutions')
    op.drop_table('positions')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_ticker'))

    op.drop_table('research_runs')
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_records_endpoint'))

    op.drop_table('provenance_records')
    op.drop_table('model_versions')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_forecasts_ticker_horizon')
        batch_op.drop_index(batch_op.f('ix_forecasts_ticker'))
        batch_op.drop_index(batch_op.f('ix_forecasts_resolve_at'))
        batch_op.drop_index(batch_op.f('ix_forecasts_input_hash'))
        batch_op.drop_index(batch_op.f('ix_forecasts_created_at'))

    op.drop_table('forecasts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
